### ISSUE TITLE
It's not even showing up.

### ISSUE THREAD

**Issue by Crispyrox** [r0ah/vitacheat#102]
Please help! Whenever I try to use Vitacheat, the menu/cheats don't show up after I press L bumper and Left on the directional pad at the same time. I did the installation right as far as I know, I followed all the steps on the wiki, checked to see if the cheats were for NoNpDrm like I needed them to be, rebooted my games and tried all of them several times and even reloaded the taiHEN config.txt. I'm on downgraded 3.60.

**Comment by RikuNoctis** [comment]
Make sure you have both vitacheat plugins (.skprx and .suprx) in their respective folders as they are specified in your config.txt.

If you have a config file on the vitacheat, delete it; it should be re-created automatically after a restart. If you can, post screenshots (or the text) of your config.txt and also of the folder structure for vitacheat.

Sometimes, vitacheat doesn't appear because the folder structure is wrong, or it may be because the .suprx plugin is not where it should. We'll try and help you solve this issue. BTW, which games/codes are you trying to use? That may help too as vitacheat doesn't play well with certain chars, which may even make it crash once you open up the menu and/or start the game.

**Comment by Crispyrox** [comment]
![basically](https://user-images.githubusercontent.com/59496145/71806179-fe300980-301c-11ea-9d8b-62f136fa8a03.png)

Sorry My editing skills aren't top notch but this is basically it. Where I put my files, what my config looks like and one of the cheats I'm trying to use.

**Comment by Crispyrox** [comment]
Sorry My editing skills aren't top notch but this is basically it. Where I put my files, what my config looks like and one of the cheats I'm trying to use.
![Inkedbasically_LI](https://user-images.githubusercontent.com/59496145/71891504-a916f500-30fb-11ea-8401-80c363475c9c.jpg)

**Comment by Crispyrox** [comment]
Does anyone have a solution?

**Comment by magicbob93** [comment]
Try to install it via AutoPlugin. 
Also, are you using enso or just henkaku?

**Comment by Crispyrox** [comment]
AutoPlugin for the win! Thank you so much!
