### ISSUE TITLE
Congratulations - This kind of projects killed the small online play community.

### ISSUE THREAD

**Issue by waltercool** [r0ah/vitacheat#133]
Congratulations to devs and players who can't legitimately win for destroying online gameplay. Hope you all feel good for this.

Now, vita can finally rest-in-peace at online servers.

**Comment by Yohoki** [comment]
...Alright.... I'll say it.

Saying the community is small is admitting that the community is already dying....

I am one of the contributors in this community. I have made codes for several games. Yes, some are Health and MP and all those things. It comes with the territory and everyone asks for these codes. I have helped others make codes, and taught people how to make them. I have even made a tool to help people make them and learn to make them.

Now, on my part, I have not made codes that work in online games. Some of the games I've made codes for have online modes, but I didn't test codes on the servers and most games require different codes for online play. I've also focused a lot on more unique codes. Codes that unlock Debug tools and items that are normally unusable. Things like Item Select menus that show items that didn't make it into the full release of games, such as in 'Dragon Quest Builders'. Or codes like the All Characters Unlocker in 'Dragon Ball Z: Battle of Z' that unlocked characters that are no longer available to purchase, or didn't make it overseas to English speaking countries. Without my code, NO ONE can download these characters now that Sony has taken them off the market. Or codes like in "Fat Princess" that allow you to use items that can no longer be purchased because you have to play online to get end of level rewards and their servers shut down years ago.

I, for one, created these codes because Vita has been dead for years and I wanted people to be able to enjoy the great games, regardless of their skill, or amount of time they could play daily. I wanted people to be able to enjoy a full game's content, regardless of if it's still available to purchase. I created these codes because it gave me a reason to continue enjoying this amazing handheld that I've loved for years.

We all really enjoyed these handhelds. Unfortunately, the handheld did not sell well outside of Japan. It was a commercial failure. I'm honestly surprised they're only now shutting things down. You've enjoyed the console. We have as well. As with all older consoles, they're being put down. Some patents are showing there may be a future handheld coming soon, and we all would appreciate a new one taking over.

If you want to continue enjoying the vita. That's fine. We have a GBATemp thread where we chat about code making and everyone on there enjoys playing the games as well. If you'd like to check out our massive list of games that have codes made for them, you're in the right place. Maybe you'll find something to make a hard game easier, or even some easy games harder, and enjoy a game however you want.

If you want to continue being a downer, please find a different place to do so.
