### ISSUE TITLE
PCSE00023 - MK9 (US) Bosses - NPC Characters

### ISSUE THREAD

**Issue by Smoker1** [r0ah/vitacheat#64]
So I was looking to see if there was any Progress made with getting the Bosses/NPC on the Vita Version, and I came to find this. But I cant find the VitaCheat Codes anywhere. Anyone else????
https://www.youtube.com/watch?v=dsuRBQWaCB8

This Mod/Codes are called: Ultimate Mortal Kombat 9 Vita

**Comment by Yohoki** [comment]
I took a quick look around... I'll send you a private message on GBATemp in a sec

**Comment by Yohoki** [comment]
We will have to see how to merge these in. But I've cleaned them up a bit and added notes/credits. It's up to you to see which version/dump it's for though. XD

~~~~
# ID: PCSE00023
# Title: Mortal Kombat
# Region: EU
# Version: ? (Needs Testing)
# Type: ? (Needs Testing)
# Code Author: White Lord (from MaxConsole) (And others. Since codes already exist for some of these.)
# Code Author: https://www.patreon.com/WhiteLord
# Code Author: https://www.youtube.com/channel/UCSfy5XgezSNmVZ9B8nuWYvQ
# Credits: Optantic (Inf Fatality Timer)
# Source: https://github.com/r0ah/vitacheat/blob/master/db/PCSE00023.psv
# Note1: This code is for 1st time run.
# Note2: Activate 1 code at a time during loading after the tower. Hold R+Start during loading screen to activate.

_V0 First Play Codes [Note1]

_V0 --Time Always at 99
$0200 81F965BC 00000063

_V0 --1P Inf HP 1st Run
$0200 8A835934 3F800000

_V0 --X-Ray
$0200 81F8CD4C 3F800000

_V0 --CPU No X-Ray
$0200 81F8DB68 00000000

_V0 --CPU Takes 2x Damage
$0200 81F8DAFC 40000000

_V0 --Auto Fatality
$0200 81F8BA54 0000000A

_V0 --9999999 Koins
$0200 81FBBDF8 0098967F

_V0 Time at 99 
$0200 81F965BC 00000063

_V0 1P Inf Health 
$0200 8A835934 3F800000

_V0 X-Ray 
$0200 81F8CD4C 3F800000

_V0 CPU No X-Ray 
$0200 81F8DB68 00000000

_V0 CPU Takes 2x Damage 
$0200 81F8DAFC 40000000

_V0 Auto Fatality 
$0200 81F8BA54 0000000A

_V0 9999999 Koins
$0200 81FBBDF8 0098967F

_V0 Inf Fatality Time
$D002 81F96988 0000000F
$0200 81F8BA48 0000000B
$0200 81F949C4 00000000
$D002 81F96988 00000000
$0200 81F8BA48 00000000
$0200 81F949C4 00000000

_V0 Play As...[Note2]
$0000 00000000 00000000

_V0 --Baraka
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843

_V0 --Goro
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C202 00000000 00000208
$0200 81F8C984 524F475F
$0200 81F8C988 0000004F

_V0 --Shao Kahn
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C203 00000000 00000208
$0200 81F8C984 4148535F
$0200 81F8C988 48414B4F
$0200 81F8C98C 0000004E

_V0 --Zombie
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C984 424D4F5A
$0200 81F8C988 4D5F4549
$0200 81F8C98C 00454C41
$0200 81F8C990 00000000
$0200 81F8C980 5F43504E

_V0 --Tremor
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C203 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 4D455254
$0200 81F8C988 0000524F

_V0 --Kintaro
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C204 00000000 00000208
$0200 81F8C980 52414843
$0200 81F8C984 4E494B5F
$0200 81F8C988 4F524154
$0200 81F8C98C 00000000

_V0 --Classic Jade
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 73616C43
$0200 81F8C988 4A636973
$0200 81F8C98C 00656461
$0200 81F8C990 00000000

_V0 --Classic Noob Saibot
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 73616C43
$0200 81F8C988 4E636973
$0200 81F8C98C 00626F6F
$0200 81F8C990 00000000

_V0 --Classic Reptile
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 73616C43
$0200 81F8C988 52636973
$0200 81F8C98C 69747065
$0200 81F8C990 0000656C

_V0 --Classic Smoke
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 73616C43
$0200 81F8C988 53636973
$0200 81F8C98C 656B6F6D
$0200 81F8C990 00006500

_V0 --Cyrax
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C206 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 65627943
$0200 81F8C988 6E694E72
$0200 81F8C98C 4C5F616A
$0200 81F8C990 3444344B
$0200 81F8C994 00000000

_V0 --Fighting Dummy
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C206 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 68676946
$0200 81F8C988 676E6974
$0200 81F8C98C 6D6D7544
$0200 81F8C990 614D5F79
$0200 81F8C994 0000656C

_V0 --Base Male
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 65736142
$0200 81F8C988 656C614D
$0200 81F8C98C 73696C00
$0200 81F8C990 006D7565

_V0 --Generic FightB
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C206 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 656E6547
$0200 81F8C988 46636972
$0200 81F8C98C 74686769
$0200 81F8C990 00427265
$0200 81F8C994 00000000

_V0 --Oni
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C206 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 4F5F4C47
$0200 81F8C988 4600696E
$0200 81F8C98C 74686769
$0200 81F8C990 00427265
$0200 81F8C994 00000000

_V0 --JC Director
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C204 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 445F434A
$0200 81F8C988 63657269
$0200 81F8C98C 00726F74

_V0 --JC Meat
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C203 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 4D5F434A
$0200 81F8C988 00746165

_V0 --Pit Fighter DG
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 465F5450
$0200 81F8C988 74686769
$0200 81F8C98C 47447265
$0200 81F8C990 00000000

_V0 --Tsung B
$0200 81F8C980 52414843
$0200 81F8C984 6168535F
$0200 81F8C988 7354676E
$0200 81F8C98C 5F676E75
$0200 81F8C990 00000062

_V0 Ladder Position
$0200 81F8F8D0 00000008

_V0 CPU is Shang Tsung
$0200 81F8F94C 52414843
$0200 81F8F950 6168535F
$0200 81F8F954 7374676E
$0200 81F8F958 5F676E75
$0200 81F8F95C 00000062

_V0 1 Goros Lair
$0200 81F8FA3C 444E4742
$0200 81F8FA40 726F475F
$0200 81F8FA44 614C736F
$0200 81F8FA48 00007269

_V0 1 Kahns Arena
$0200 81F8FA3C 444E4742
$0200 81F8FA40 68614B5F
$0200 81F8FA44 6F43736E
$0200 81F8FA48 6573696C
$0200 81F8FA4C 00006D75

_V0 Background is...[Pick 1]
$0000 00000000 00000000

_V0 --Goros Lair
$0200 81F8FBA4 444E4742
$0200 81F8FBA8 726F475F
$0200 81F8FBAC 614C736F
$0200 81F8FBB0 00007269
$0200 81F8FD0C 444E4742
$0200 81F8FD10 726F475F
$0200 81F8FD14 614C736F
$0200 81F8FD18 00007269
$0200 81F8FE74 444E4742
$0200 81F8FE78 726F475F
$0200 81F8FE7C 614C736F
$0200 81F8FE80 00007269
$0200 81F8FFDC 444E4742
$0200 81F8FFE0 726F475F
$0200 81F8FFE4 614C736F
$0200 81F8FFE8 00007269
$0200 81F90144 444E4742
$0200 81F90148 726F475F
$0200 81F9014C 614C736F
$0200 81F90150 00007269
$0200 81F902AC 444E4742
$0200 81F902B0 726F475F
$0200 81F902B4 614C736F
$0200 81F902B8 00007269
$0200 81F90414 444E4742
$0200 81F90418 726F475F
$0200 81F9041C 614C736F
$0200 81F90420 00007269
$0200 81F9057C 444E4742
$0200 81F90580 726F475F
$0200 81F90584 614C736F
$0200 81F90588 00007269
$0200 81F906E4 444E4742
$0200 81F906E8 726F475F
$0200 81F906EC 614C736F
$0200 81F906F0 00007269

_V0 --Kahns Arena
$0200 81F8FA3C 444E4742
$0200 81F8FA40 68614B5F
$0200 81F8FA44 6F43736E
$0200 81F8FA48 6573696C
$0200 81F8FA4C 00006D75
$0200 81F8FBA4 444E4742
$0200 81F8FBA8 68614B5F
$0200 81F8FBAC 6F43736E
$0200 81F8FBB0 6573696C
$0200 81F8FBB4 00006D75
$0200 81F8FD0C 444E4742
$0200 81F8FD10 68614B5F
$0200 81F8FD14 6F43736E
$0200 81F8FD18 6573696C
$0200 81F8FD1C 00006D75
$0200 81F8FE74 444E4742
$0200 81F8FE78 68614B5F
$0200 81F8FE7C 6F43736E
$0200 81F8FE80 6573696C
$0200 81F8FE84 00006D75
$0200 81F8FFDC 444E4742
$0200 81F8FFE0 68614B5F
$0200 81F8FFE4 6F43736E
$0200 81F8FFE8 6573696C
$0200 81F8FFEC 00006D75
$0200 81F90144 444E4742
$0200 81F90148 68614B5F
$0200 81F9014C 6F43736E
$0200 81F90150 6573696C
$0200 81F90154 00006D75
$0200 81F902AC 444E4742
$0200 81F902B0 68614B5F
$0200 81F902B4 6F43736E
$0200 81F902B8 6573696C
$0200 81F902BC 00006D75
$0200 81F90414 444E4742
$0200 81F90418 68614B5F
$0200 81F9041C 6F43736E
$0200 81F90420 6573696C
$0200 81F90424 00006D75
$0200 81F9057C 444E4742
$0200 81F90580 68614B5F
$0200 81F90584 6F43736E
$0200 81F90588 6573696C
$0200 81F9058C 00006D75
$0200 81F906E4 444E4742
$0200 81F906E8 68614B5F
$0200 81F906EC 6F43736E
$0200 81F906F0 6573696C
$0200 81F906F4 00006D75
~~~~

**Comment by Lsidjsdjk** [comment]
# ID: PCSE00023
# Title: Mortal Kombat
# Region: EU
# Version: ? (Needs Testing)
# Type: ? (Needs Testing)
# Code Author: White Lord (from MaxConsole) (And others. Since codes already exist for some of these.)
# Code Author: https://www.patreon.com/WhiteLord
# Code Author: https://www.youtube.com/channel/UCSfy5XgezSNmVZ9B8nuWYvQ
# Credits: Optantic (Inf Fatality Timer)
# Source: https://github.com/r0ah/vitacheat/blob/master/db/PCSE00023.psv
# Note1: This code is for 1st time run.
# Note2: Activate 1 code at a time during loading after the tower. Hold R+Start during loading screen to activate.

_V0 First Play Codes [Note1]

_V0 --Time Always at 99
$0200 81F965BC 00000063

_V0 --1P Inf HP 1st Run
$0200 8A835934 3F800000

_V0 --X-Ray
$0200 81F8CD4C 3F800000

_V0 --CPU No X-Ray
$0200 81F8DB68 00000000

_V0 --CPU Takes 2x Damage
$0200 81F8DAFC 40000000

_V0 --Auto Fatality
$0200 81F8BA54 0000000A

_V0 --9999999 Koins
$0200 81FBBDF8 0098967F

_V0 Time at 99 
$0200 81F965BC 00000063

_V0 1P Inf Health 
$0200 8A835934 3F800000

_V0 X-Ray 
$0200 81F8CD4C 3F800000

_V0 CPU No X-Ray 
$0200 81F8DB68 00000000

_V0 CPU Takes 2x Damage 
$0200 81F8DAFC 40000000

_V0 Auto Fatality 
$0200 81F8BA54 0000000A

_V0 9999999 Koins
$0200 81FBBDF8 0098967F

_V0 Inf Fatality Time
$D002 81F96988 0000000F
$0200 81F8BA48 0000000B
$0200 81F949C4 00000000
$D002 81F96988 00000000
$0200 81F8BA48 00000000
$0200 81F949C4 00000000

_V0 Play As...[Note2]
$0000 00000000 00000000

_V0 --Baraka
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843

_V0 --Goro
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C202 00000000 00000208
$0200 81F8C984 524F475F
$0200 81F8C988 0000004F

_V0 --Shao Kahn
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C203 00000000 00000208
$0200 81F8C984 4148535F
$0200 81F8C988 48414B4F
$0200 81F8C98C 0000004E

_V0 --Zombie
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C984 424D4F5A
$0200 81F8C988 4D5F4549
$0200 81F8C98C 00454C41
$0200 81F8C990 00000000
$0200 81F8C980 5F43504E

_V0 --Tremor
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C203 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 4D455254
$0200 81F8C988 0000524F

_V0 --Kintaro
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C204 00000000 00000208
$0200 81F8C980 52414843
$0200 81F8C984 4E494B5F
$0200 81F8C988 4F524154
$0200 81F8C98C 00000000

_V0 --Classic Jade
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 73616C43
$0200 81F8C988 4A636973
$0200 81F8C98C 00656461
$0200 81F8C990 00000000

_V0 --Classic Noob Saibot
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 73616C43
$0200 81F8C988 4E636973
$0200 81F8C98C 00626F6F
$0200 81F8C990 00000000

_V0 --Classic Reptile
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 73616C43
$0200 81F8C988 52636973
$0200 81F8C98C 69747065
$0200 81F8C990 0000656C

_V0 --Classic Smoke
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 73616C43
$0200 81F8C988 53636973
$0200 81F8C98C 656B6F6D
$0200 81F8C990 00006500

_V0 --Cyrax
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C206 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 65627943
$0200 81F8C988 6E694E72
$0200 81F8C98C 4C5F616A
$0200 81F8C990 3444344B
$0200 81F8C994 00000000

_V0 --Fighting Dummy
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C206 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 68676946
$0200 81F8C988 676E6974
$0200 81F8C98C 6D6D7544
$0200 81F8C990 614D5F79
$0200 81F8C994 0000656C

_V0 --Base Male
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 65736142
$0200 81F8C988 656C614D
$0200 81F8C98C 73696C00
$0200 81F8C990 006D7565

_V0 --Generic FightB
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C206 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 656E6547
$0200 81F8C988 46636972
$0200 81F8C98C 74686769
$0200 81F8C990 00427265
$0200 81F8C994 00000000

_V0 --Oni
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C206 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 4F5F4C47
$0200 81F8C988 4600696E
$0200 81F8C98C 74686769
$0200 81F8C990 00427265
$0200 81F8C994 00000000

_V0 --JC Director
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C204 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 445F434A
$0200 81F8C988 63657269
$0200 81F8C98C 00726F74

_V0 --JC Meat
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C203 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 4D5F434A
$0200 81F8C988 00746165

_V0 --Pit Fighter DG
$0200 81F8C984 5241425F
$0200 81F8C988 00414B41
$0200 81F8C980 52414843
$C205 00000000 00000208
$0200 81F8C980 5F43504E
$0200 81F8C984 465F5450
$0200 81F8C988 74686769
$0200 81F8C98C 47447265
$0200 81F8C990 00000000

_V0 --Tsung B
$0200 81F8C980 52414843
$0200 81F8C984 6168535F
$0200 81F8C988 7354676E
$0200 81F8C98C 5F676E75
$0200 81F8C990 00000062

_V0 Ladder Position
$0200 81F8F8D0 00000008

_V0 CPU is Shang Tsung
$0200 81F8F94C 52414843
$0200 81F8F950 6168535F
$0200 81F8F954 7374676E
$0200 81F8F958 5F676E75
$0200 81F8F95C 00000062

_V0 1 Goros Lair
$0200 81F8FA3C 444E4742
$0200 81F8FA40 726F475F
$0200 81F8FA44 614C736F
$0200 81F8FA48 00007269

_V0 1 Kahns Arena
$0200 81F8FA3C 444E4742
$0200 81F8FA40 68614B5F
$0200 81F8FA44 6F43736E
$0200 81F8FA48 6573696C
$0200 81F8FA4C 00006D75

_V0 Background is...[Pick 1]
$0000 00000000 00000000

_V0 --Goros Lair
$0200 81F8FBA4 444E4742
$0200 81F8FBA8 726F475F
$0200 81F8FBAC 614C736F
$0200 81F8FBB0 00007269
$0200 81F8FD0C 444E4742
$0200 81F8FD10 726F475F
$0200 81F8FD14 614C736F
$0200 81F8FD18 00007269
$0200 81F8FE74 444E4742
$0200 81F8FE78 726F475F
$0200 81F8FE7C 614C736F
$0200 81F8FE80 00007269
$0200 81F8FFDC 444E4742
$0200 81F8FFE0 726F475F
$0200 81F8FFE4 614C736F
$0200 81F8FFE8 00007269
$0200 81F90144 444E4742
$0200 81F90148 726F475F
$0200 81F9014C 614C736F
$0200 81F90150 00007269
$0200 81F902AC 444E4742
$0200 81F902B0 726F475F
$0200 81F902B4 614C736F
$0200 81F902B8 00007269
$0200 81F90414 444E4742
$0200 81F90418 726F475F
$0200 81F9041C 614C736F
$0200 81F90420 00007269
$0200 81F9057C 444E4742
$0200 81F90580 726F475F
$0200 81F90584 614C736F
$0200 81F90588 00007269
$0200 81F906E4 444E4742
$0200 81F906E8 726F475F
$0200 81F906EC 614C736F
$0200 81F906F0 00007269

_V0 --Kahns Arena
$0200 81F8FA3C 444E4742
$0200 81F8FA40 68614B5F
$0200 81F8FA44 6F43736E
$0200 81F8FA48 6573696C
$0200 81F8FA4C 00006D75
$0200 81F8FBA4 444E4742
$0200 81F8FBA8 68614B5F
$0200 81F8FBAC 6F43736E
$0200 81F8FBB0 6573696C
$0200 81F8FBB4 00006D75
$0200 81F8FD0C 444E4742
$0200 81F8FD10 68614B5F
$0200 81F8FD14 6F43736E
$0200 81F8FD18 6573696C
$0200 81F8FD1C 00006D75
$0200 81F8FE74 444E4742
$0200 81F8FE78 68614B5F
$0200 81F8FE7C 6F43736E
$0200 81F8FE80 6573696C
$0200 81F8FE84 00006D75
$0200 81F8FFDC 444E4742
$0200 81F8FFE0 68614B5F
$0200 81F8FFE4 6F43736E
$0200 81F8FFE8 6573696C
$0200 81F8FFEC 00006D75
$0200 81F90144 444E4742
$0200 81F90148 68614B5F
$0200 81F9014C 6F43736E
$0200 81F90150 6573696C
$0200 81F90154 00006D75
$0200 81F902AC 444E4742
$0200 81F902B0 68614B5F
$0200 81F902B4 6F43736E
$0200 81F902B8 6573696C
$0200 81F902BC 00006D75
$0200 81F90414 444E4742
$0200 81F90418 68614B5F
$0200 81F9041C 6F43736E
$0200 81F90420 6573696C
$0200 81F90424 00006D75
$0200 81F9057C 444E4742
$0200 81F90580 68614B5F
$0200 81F90584 6F43736E
$0200 81F90588 6573696C
$0200 81F9058C 00006D75
$0200 81F906E4 444E4742
$0200 81F906E8 68614B5F
$0200 81F906EC 6F43736E
$0200 81F906F0 6573696C
$0200 81F906F4 00006D75
