### ISSUE TITLE
Tales of Hearts R PCSE00429

### ISSUE THREAD

**Issue by Peoples00** [r0ah/vitacheat#78]
the cheats for Tales of Hearts R US do not work so it's just the Inf HP and Inf TP because if I activate the two then the HP and TP are at 0

**Comment by RikuNoctis** [comment]
Are you sure you are playing the 1.0 version of the game? Those codes do work for the 1.0 version on NoNpDrm.

**Comment by Yohoki** [comment]
This could also be an issue with system language again. I know we ran into this issue on DBZ:BoZ. I would like to take some time soon to do some pointer searching with my new program and see if the language problems can be fixed with stronger pointers.

In the meantime, the codes are MOV type codes, so the effect you're having is giving me an idea to try to fix them. Try this code for me:
~~~~
_V0 Inf HP
$0100 81295418 0000270F
$0100 81295A50 0000270F
$0100 81296088 0000270F
$0100 812966C0 0000270F
$0100 81296CF8 0000270F
$0100 81297330 0000270F
$0100 81297968 0000270F
$0100 81297FA0 0000270F
~~~~
Hopefully it sets your HP to max.

**Comment by Yohoki** [comment]
And inf TP:
~~~~
_V0 Inf TP
$5100 8129541A 0000270F
$5100 81295A52 0000270F
$5100 8129608A 0000270F
$5100 812966C2 0000270F
$5100 81296CFA 0000270F
$5100 81297332 0000270F
$5100 8129796A 0000270F
$5100 81297FA2 0000270F
~~~~

**Comment by Peoples00** [comment]
@RikuNoctis yes I play it on 1.0 version of the game but I guess it is due to the system language because the other codes work

@Yohoki thanks for the codes that work
