### ISSUE TITLE
vitacheat cant change values c2-12828-1

### ISSUE THREAD

**Issue by broomop** [r0ah/vitacheat#88]
vitacheat cant change values c2-12828-1 have latest vitacheat and tried some others i try edit anything and it crashes out. why?

**Comment by RikuNoctis** [comment]
Which game? Gundam Extreme VS Force?

This happens with certain games. The game may even have some kind of "anti-tampering for memory module" based on the game engine it uses (even some PSP games had it way back). Have you tried making dumps and searching values from there? While it will take longer (maybe?) because you need to do it on a PC, you may at least get something from it if the game crashes every time you search for something. I know, it's not ideal, but it's something.

**Comment by broomop** [comment]
I only tried on the 0x8x range so it might be protected. i tried it on random things on my psvita even homebrew like vitashell. it would just crash out... im new to this stuff on vita. I can do direct eboot edits on retail but even the rebuilt ones just crash when trying to edit. I was wondering if i was missing something. I not had search to even show any results yet since if i cannot change value it seems pointless.

**Comment by RikuNoctis** [comment]
Which firmware are you using? If you are on 3.70 Vitacheat (and some other plugins) may cause issues.

I can try to test the game so we can at least confirm if the issue is on your part (maybe your setup) or the game simply refuses to change things with Vitacheat. For that I will need the name and version of the game (or the title ID, which is easier).

**Comment by broomop** [comment]
its fine thanks for your time i got it working. it was the fact i was editing in the wrong area.

thanks.
